const randomKiwi = {};

// array of objects with words and definitions as keys.
randomKiwi.dataBase = [
    {
        word: `Togs`,
        definition: `<h3>You wear them swimming!</h3><p>Togs is the collective term for all forms of swim-wear (board shorts, bikinis, one-piece, speedos ect).</p>`
    },
    {
        word: `Jandals`,
        definition: `<h3>Flip-flops!</h3><p>The origin of this word is "Japanese Sandals"</p>`
    },
    {
        word: `Dairy`,
        definition: `<h3>Convenience Store!</h3><p>Usually a local corner store, will sell essentials and treats.</p>`
    },
    {
        word: `Wop Wops`,
        definition: `<h3>The middle of no-where!</h3><p>The wop wops is far away from or not surrounded by human activity. Could mean both rural or wild areas</p>`
    },
    {
        word: `Kiwi`,
        definition: `<h3>NOT THE FRUIT!</h3><p>1) A Kiwi refers to the flightless bird that is the national symbol of New Zealand.</p><p>2) Someone from New Zealand is also known as a Kiwi. For the fruit please see 'Kiwi-fruit'.</p>`
    },
    {
        word: `Bach`,
        definition: `<h3>A little house for vacations!</h3><p>Similar to a Canadian "Cottage", a Bach is a small property usually near the beach to enjoy in summer.</p>`
    },
    {
        word: `Tramping`,
        definition: `<h3>Hiking!</h3><p>Going tramping is a popular activity in New Zealand.</p>`
    },
    {
        word: `Yarn`,
        definition: `<h3>Telling a story!</h3><p>Chatting with someone, specifically the act of telling a story would be considered "Having a yarn".</p>`
    },
    {
        word: `Cuz / Cuzzie`,
        definition: `<h3>Cousin</h3><p>Cuz or Cuzzie is short for Cousin but can mean anyone close to you that is like family.</p>`
    },
    {
        word: `Munted`,
        definition: `<h3>Broken!</h3><p>If something is "Munted" it could also be described as broken, ruined, damaged, or fucked up.</p>`
    }
]


// Function for generating a random number 

randomKiwi.randomItemFromData = function(array) {
    const randomNumber = Math.floor(Math.random() * this.dataBase.length);
    return array[randomNumber];
}

// listen for user event on button click
randomKiwi.buttonClick = function(){
    $('form').on('submit', function(event) {
        event.preventDefault();
 
        // generate a random number and use get a index of the array
        const userClick = randomKiwi.randomItemFromData(randomKiwi.dataBase);
        
        // Clear the content potentially generated by previous click.
        // display matching word and definition to user by adding to html
        $('.results').html(`<h2>${userClick.word}</h2><p>${userClick.definition}`)
    });    
}

// smooth scroll to results when button clicked
randomKiwi.smoothScroll = function () {
    $('form').on('submit', function (event) {
        // store content of data hash (which refers to the new location)
        const resultsPage = $('input').data('hash');
        
        // if there is something in the hash prevent default behavior and then
        if (resultsPage !== '') {
            event.preventDefault();
        //  and then animate the change in locations to the new location
            $('html, body').animate({
                scrollTop: $(resultsPage).offset().top
            }, 800, function () {
                    window.location.hash = "resultsPage";
            });
        } 
        
    });
}

// fix for page refresh to move to top
randomKiwi.resetHash = function () {
    window.location.hash = "";
}

$(function(){
    // $(window).scrollTop(0);
    randomKiwi.resetHash();
    randomKiwi.smoothScroll();
    randomKiwi.buttonClick();
});
